package lol

import "time"

type Lol struct {
	ID          int64     `json:"id" gorm:"id"`
	UpdateVer   int64     `json:"update_ver" gorm:"update_ver"`
	Title       string    `json:"title" gorm:"title"`
	Url         string    `json:"url" gorm:"url"`
	Time        string    `json:"time" gorm:"time"`
	CreatedTime time.Time `json:"create_time" gorm:"create_time"`
	UpdatedTime time.Time `json:"update_time" gorm:"update_time"`
}

func (l *Lol) TableName() string {
	return "lol"
}

type Ret struct {
	Data Data
}
type Data struct {
	Result []*Result `json:"result"`
}
type Result struct {
	SIdxTime string `json:"sIdxTime"`
	STitle   string `json:"sTitle"`
	IDocId   string `json:"iDocId"`
}
type ResData struct {
	Id        string `json:"id" gorm:"id"`
	Title     string `json:"title" gorm:"title"`
	Pic       string `json:"pic" gorm:"pic"`
	Hot       int    `json:"hot" gorm:"hot"`
	MobileUrl string `json:"mobile_url" gorm:"mobile_url"`
}

type AutoGenerated struct {
	AdSearchList any         `json:"ad_search_list"`
	BannerDark   BannerDark  `json:"banner_dark"`
	BannerLight  BannerLight `json:"banner_light"`
	BoardTabs    any         `json:"board_tabs"`
	Data         Data        `json:"data"`
	Extra        Extra       `json:"extra"`
	LogPb        LogPb       `json:"log_pb"`
	StatusCode   int         `json:"status_code"`
}
type BannerDark struct {
	URI     string   `json:"uri"`
	URLList []string `json:"url_list"`
}
type BannerLight struct {
	URI     string   `json:"uri"`
	URLList []string `json:"url_list"`
}
type ShareInfo struct {
	ShareLinkDesc string `json:"share_link_desc"`
	ShareTitle    string `json:"share_title"`
	ShareURL      string `json:"share_url"`
}
type WordCover struct {
	URI     string   `json:"uri"`
	URLList []string `json:"url_list"`
}
type TrendingList struct {
	ArticleDetailCount int       `json:"article_detail_count"`
	AwemeInfos         any       `json:"aweme_infos"`
	DiscussVideoCount  int       `json:"discuss_video_count"`
	DisplayStyle       int       `json:"display_style,omitempty"`
	DriftInfo          any       `json:"drift_info"`
	EventTime          int       `json:"event_time"`
	GroupID            string    `json:"group_id"`
	HotValue           int       `json:"hot_value"`
	HotlistParam       string    `json:"hotlist_param"`
	Label              int       `json:"label"`
	RelatedWords       any       `json:"related_words"`
	SentenceID         string    `json:"sentence_id"`
	SentenceTag        int       `json:"sentence_tag"`
	VideoCount         int       `json:"video_count"`
	Word               string    `json:"word"`
	WordCover          WordCover `json:"word_cover"`
	WordSubBoard       any       `json:"word_sub_board"`
	WordType           int       `json:"word_type"`
}
type TopicInfo struct {
}
type WordList struct {
	AwemeInfos         any       `json:"aweme_infos"`
	CanExtendDetail    bool      `json:"can_extend_detail"`
	DiscussVideoCount  int       `json:"discuss_video_count"`
	DriftInfo          any       `json:"drift_info"`
	HotValue           int       `json:"hot_value"`
	HotlistParam       string    `json:"hotlist_param"`
	Label              int       `json:"label"`
	RelatedWords       any       `json:"related_words"`
	SentenceID         string    `json:"sentence_id"`
	TopicInfo          TopicInfo `json:"topic_info,omitempty"`
	ViewCount          int       `json:"view_count"`
	Word               string    `json:"word"`
	WordSubBoard       any       `json:"word_sub_board"`
	WordType           int       `json:"word_type"`
	ArticleDetailCount int       `json:"article_detail_count,omitempty"`
	DisplayStyle       int       `json:"display_style,omitempty"`
	EventTime          int       `json:"event_time,omitempty"`
	GroupID            string    `json:"group_id,omitempty"`
	Position           int       `json:"position,omitempty"`
	SentenceTag        int       `json:"sentence_tag,omitempty"`
	VideoCount         int       `json:"video_count,omitempty"`
	WordCover          WordCover `json:"word_cover,omitempty"`
	RoomCount          int       `json:"room_count,omitempty"`
}

type Extra struct {
	FatalItemIds []any  `json:"fatal_item_ids"`
	Logid        string `json:"logid"`
	Now          int64  `json:"now"`
}
type LogPb struct {
	ImprID string `json:"impr_id"`
}
