package juejin

import "time"

type Juejin struct {
	ID          int64     `json:"id" form:"id" gorm:"id"`
	Hot         int64     `json:"hot" form:"hot" gorm:"hot"`
	UpdateVer   int64     `json:"update_ver" form:"update_ver" gorm:"update_ver"`
	Title       string    `json:"title" form:"title" gorm:"title"`
	Url         string    `json:"url" form:"url" gorm:"url"`
	AuthorId    string    `json:"author_id" form:"author_id" gorm:"author_id"`
	AuthorName  string    `json:"author_name" form:"author_name" gorm:"author_name"`
	CreatedTime time.Time `json:"created_time" form:"created_time" gorm:"created_time"`
	UpdatedTime time.Time `json:"updated_time" form:"updated_time" gorm:"updated_time"`
}

// TableName 表名称
func (Juejin) TableName() string {
	return "juejin"
}

type AutoGenerated struct {
	ErrNo  int    `json:"err_no"`
	ErrMsg string `json:"err_msg"`
	Data   []Data `json:"data"`
}
type Data struct {
	Content        Content        `json:"content"`
	ContentCounter ContentCounter `json:"content_counter"`
	Author         Author         `json:"author"`
	AuthorCounter  AuthorCounter  `json:"author_counter"`
	UserInteract   UserInteract   `json:"user_interact"`
}
type Content struct {
	ContentID  string   `json:"content_id"`
	ItemType   int      `json:"item_type"`
	Format     string   `json:"format"`
	AuthorID   string   `json:"author_id"`
	Title      string   `json:"title"`
	Brief      string   `json:"brief"`
	Status     int      `json:"status"`
	Ctime      int      `json:"ctime"`
	Mtime      int      `json:"mtime"`
	CategoryID string   `json:"category_id"`
	TagIds     []string `json:"tag_ids"`
}
type ContentCounter struct {
	View          int `json:"view"`
	Like          int `json:"like"`
	Collect       int `json:"collect"`
	HotRank       int `json:"hot_rank"`
	CommentCount  int `json:"comment_count"`
	InteractCount int `json:"interact_count"`
}
type Author struct {
	UserID     string `json:"user_id"`
	Name       string `json:"name"`
	Avatar     string `json:"avatar"`
	IsFollowed bool   `json:"is_followed"`
}
type AuthorCounter struct {
	Level    int   `json:"level"`
	Power    int   `json:"power"`
	Follower int   `json:"follower"`
	Followee int   `json:"followee"`
	Publish  int   `json:"publish"`
	View     int   `json:"view"`
	Like     int   `json:"like"`
	HotRank  int64 `json:"hot_rank"`
}
type UserInteract struct {
	IsUserLike    bool `json:"is_user_like"`
	IsUserCollect bool `json:"is_user_collect"`
	IsFollow      bool `json:"is_follow"`
}
