package weibo

import "time"

type WeiBo struct {
	ID          int64     `json:"id" gorm:"id"`
	Title       string    `json:"title" gorm:"title"`
	UpdateVer   int64     `json:"update_ver" gorm:"update_ver"`
	Hot         int       `json:"hot" gorm:"hot"`
	Url         string    `json:"url" gorm:"url"`
	IconDesc    string    `json:"icon_desc" gorm:"icon_desc"`
	Category    string    `json:"category" gorm:"category"`
	CreatedTime time.Time `json:"created_time" gorm:"created_time"`
	UpdatedTime time.Time `json:"updated_time" gorm:"updated_time"`
}

// TableName 表名称
func (WeiBo) TableName() string {
	return "weibo"
}

type Response struct {
	Ok   int `json:"ok"`
	Data struct {
		HotGov   HotGov     `json:"hot_gov"`
		Realtime []Realtime `json:"realtime"`
	} `json:"data"`
}
type HotGov struct {
}
type Realtime struct {
	Flag     int    `json:"flag"`
	RealPos  int    `json:"realpos"`
	RawHot   int    `json:"raw_hot"`
	Note     string `json:"note"`
	IconDesc string `json:"icon_desc"`
	Category string `json:"category"`
}
type AutoGenerated struct {
	Ok   int  `json:"ok"`
	Data Data `json:"data"`
}
type StarName struct {
}
type PcIcon struct {
	FinderDescColor string `json:"finder_desc_color"`
	BandDesc        string `json:"band_desc"`
	BandDescColor   string `json:"band_desc_color"`
	FinderDesc      string `json:"finder_desc"`
}
type MobileIcon struct {
	Band       string `json:"band"`
	FinderGrey string `json:"finder_grey"`
	Width      int    `json:"width"`
	Height     int    `json:"height"`
	BandGrey   string `json:"band_grey"`
	Finder     string `json:"finder"`
}
type Pc struct {
	PcClick string `json:"pc_click"`
	Type    string `json:"type"`
	PcShow  string `json:"pc_show"`
}
type App struct {
	ThirdPartyShow  string `json:"third_party_show"`
	ThirdPartyClick string `json:"third_party_click"`
	Type            string `json:"type"`
	MonitorName     string `json:"monitor_name,omitempty"`
}
type Monitors struct {
	Pc  []Pc  `json:"pc"`
	App []App `json:"app"`
}
type Monitor struct {
}
type MobileIconSocialize struct {
	Band       string `json:"band"`
	FinderGrey string `json:"finder_grey"`
	Width      int    `json:"width"`
	BandGrey   string `json:"band_grey"`
	Finder     string `json:"finder"`
	Height     int    `json:"height"`
}
type Material struct {
}
type Hotgovs struct {
	TopicFlag          int    `json:"topic_flag"`
	Name               string `json:"name"`
	IsGov              int    `json:"is_gov"`
	Pos                int    `json:"pos"`
	Mid                string `json:"mid"`
	Stime              int    `json:"stime"`
	SmallIconDescColor string `json:"small_icon_desc_color"`
	Note               string `json:"note"`
	IsHot              int    `json:"is_hot"`
	URL                string `json:"url"`
	IconDesc           string `json:"icon_desc"`
	Word               string `json:"word"`
	IconDescColor      string `json:"icon_desc_color"`
	Flag               int    `json:"flag"`
	SmallIconDesc      string `json:"small_icon_desc"`
}
type Hotgov struct {
	TopicFlag          int    `json:"topic_flag"`
	Name               string `json:"name"`
	IsGov              int    `json:"is_gov"`
	Pos                int    `json:"pos"`
	Mid                string `json:"mid"`
	Stime              int    `json:"stime"`
	SmallIconDescColor string `json:"small_icon_desc_color"`
	Note               string `json:"note"`
	IsHot              int    `json:"is_hot"`
	URL                string `json:"url"`
	IconDesc           string `json:"icon_desc"`
	Word               string `json:"word"`
	IconDescColor      string `json:"icon_desc_color"`
	Flag               int    `json:"flag"`
	SmallIconDesc      string `json:"small_icon_desc"`
}
type Data struct {
	Realtime []Realtime `json:"realtime"`
	Hotgovs  []Hotgovs  `json:"hotgovs"`
	Hotgov   Hotgov     `json:"hotgov"`
}
