package hyper

import "time"

type Hyper struct {
	ID          int64     `json:"id" gorm:"id"`
	UpdateVer   int64     `json:"update_ver" gorm:"update_ver"`
	Title       string    `json:"title" gorm:"title"`
	KeyWord     string    `json:"KeyWord" gorm:"key_word"`
	Url         string    `json:"url" gorm:"url"`
	CreatedTime time.Time `json:"create_time" gorm:"create_time"`
	UpdatedTime time.Time `json:"update_time" gorm:"update_time"`
}

func (h *Hyper) TableName() string {
	return "hyper"
}

type Ret struct {
	ResultCode int    `json:"result_code" gorm:"result_code"`
	ResultMsg  string `json:"result_msg" gorm:"result_msg"`
	SystemTime int64  `json:"system_time" gorm:"system_time"`
	Data       Date
}
type Date struct {
	HotNews []*HotNews `json:"hotNews" gorm:"hot_news"`
}
type HotNews struct {
	ContId  string     `json:"contId" gorm:"cont_id"`
	Name    string     `json:"name" gorm:"name"`
	TagList []*TagList `json:"tagList" gorm:"tag_list"`
}
type TagList struct {
	Tag string `json:"tag" gorm:"tag"`
}
type AutoGenerated struct {
	AdSearchList any         `json:"ad_search_list"`
	BannerDark   BannerDark  `json:"banner_dark"`
	BannerLight  BannerLight `json:"banner_light"`
	BoardTabs    any         `json:"board_tabs"`
	Data         Data        `json:"data"`
	Extra        Extra       `json:"extra"`
	LogPb        LogPb       `json:"log_pb"`
	StatusCode   int         `json:"status_code"`
}
type BannerDark struct {
	URI     string   `json:"uri"`
	URLList []string `json:"url_list"`
}
type BannerLight struct {
	URI     string   `json:"uri"`
	URLList []string `json:"url_list"`
}
type ShareInfo struct {
	ShareLinkDesc string `json:"share_link_desc"`
	ShareTitle    string `json:"share_title"`
	ShareURL      string `json:"share_url"`
}
type WordCover struct {
	URI     string   `json:"uri"`
	URLList []string `json:"url_list"`
}
type TrendingList struct {
	ArticleDetailCount int       `json:"article_detail_count"`
	AwemeInfos         any       `json:"aweme_infos"`
	DiscussVideoCount  int       `json:"discuss_video_count"`
	DisplayStyle       int       `json:"display_style,omitempty"`
	DriftInfo          any       `json:"drift_info"`
	EventTime          int       `json:"event_time"`
	GroupID            string    `json:"group_id"`
	HotValue           int       `json:"hot_value"`
	HotlistParam       string    `json:"hotlist_param"`
	Label              int       `json:"label"`
	RelatedWords       any       `json:"related_words"`
	SentenceID         string    `json:"sentence_id"`
	SentenceTag        int       `json:"sentence_tag"`
	VideoCount         int       `json:"video_count"`
	Word               string    `json:"word"`
	WordCover          WordCover `json:"word_cover"`
	WordSubBoard       any       `json:"word_sub_board"`
	WordType           int       `json:"word_type"`
}
type TopicInfo struct {
}
type WordList struct {
	AwemeInfos         any       `json:"aweme_infos"`
	CanExtendDetail    bool      `json:"can_extend_detail"`
	DiscussVideoCount  int       `json:"discuss_video_count"`
	DriftInfo          any       `json:"drift_info"`
	HotValue           int       `json:"hot_value"`
	HotlistParam       string    `json:"hotlist_param"`
	Label              int       `json:"label"`
	RelatedWords       any       `json:"related_words"`
	SentenceID         string    `json:"sentence_id"`
	TopicInfo          TopicInfo `json:"topic_info,omitempty"`
	ViewCount          int       `json:"view_count"`
	Word               string    `json:"word"`
	WordSubBoard       any       `json:"word_sub_board"`
	WordType           int       `json:"word_type"`
	ArticleDetailCount int       `json:"article_detail_count,omitempty"`
	DisplayStyle       int       `json:"display_style,omitempty"`
	EventTime          int       `json:"event_time,omitempty"`
	GroupID            string    `json:"group_id,omitempty"`
	Position           int       `json:"position,omitempty"`
	SentenceTag        int       `json:"sentence_tag,omitempty"`
	VideoCount         int       `json:"video_count,omitempty"`
	WordCover          WordCover `json:"word_cover,omitempty"`
	RoomCount          int       `json:"room_count,omitempty"`
}
type Data struct {
	ActiveTime    string         `json:"active_time"`
	RecommendList any            `json:"recommend_list"`
	ShareInfo     ShareInfo      `json:"share_info"`
	TrendingDesc  string         `json:"trending_desc"`
	TrendingList  []TrendingList `json:"trending_list"`
	WordList      []WordList     `json:"word_list"`
}
type Extra struct {
	FatalItemIds []any  `json:"fatal_item_ids"`
	Logid        string `json:"logid"`
	Now          int64  `json:"now"`
}
type LogPb struct {
	ImprID string `json:"impr_id"`
}
