package toutiao

import "time"

type TouTiao struct {
	ID          int64     `json:"id" gorm:"id"`
	UpdateVer   int64     `json:"update_ver" gorm:"update_ver"`
	Title       string    `json:"title" gorm:"title"`
	Icon        string    `json:"icon" gorm:"icon"`
	Url         string    `json:"url" gorm:"url"`
	Hot         string    `json:"hot" gorm:"hot"`
	LabelDesc   string    `json:"label_desc" gorm:"label_desc"`
	CreatedTime time.Time `json:"created_time" gorm:"created_time"`
	UpdatedTime time.Time `json:"updated_time" gorm:"updated_time"`
}

// TableName 表名称
func (*TouTiao) TableName() string {
	return "toutiao"
}

type Hot struct {
	List []ResDate `json:"data" gorm:"list"`
}
type ResDate struct {
	Title     string `json:"Title" gorm:"title"`
	Label     string `json:"label" gorm:"label"`
	Hot       string `json:"HotValue" gorm:"hot"`
	Url       string `json:"Url" gorm:"url"`
	LabelDesc string `json:"QueryWord" gorm:"QueryWord"`
}
type AutoGenerated struct {
	Data          []Data         `json:"data"`
	FixedTopData  []FixedTopData `json:"fixed_top_data"`
	FixedTopStyle string         `json:"fixed_top_style"`
	ImprID        string         `json:"impr_id"`
	Status        string         `json:"status"`
}
type URLList struct {
	URL string `json:"url"`
}
type LabelURI struct {
	URI       string    `json:"uri"`
	URL       string    `json:"url"`
	Width     int       `json:"width"`
	Height    int       `json:"height"`
	URLList   []URLList `json:"url_list"`
	ImageType int       `json:"image_type"`
}
type Image struct {
	URI       string    `json:"uri"`
	URL       string    `json:"url"`
	Width     int       `json:"width"`
	Height    int       `json:"height"`
	URLList   []URLList `json:"url_list"`
	ImageType int       `json:"image_type"`
}
type Data struct {
	ClusterID        int64    `json:"ClusterId"`
	Title            string   `json:"Title"`
	LabelURL         string   `json:"LabelUrl"`
	Label            string   `json:"Label"`
	URL              string   `json:"Url"`
	HotValue         string   `json:"HotValue"`
	Schema           string   `json:"Schema"`
	LabelURI         LabelURI `json:"LabelUri"`
	ClusterIDStr     string   `json:"ClusterIdStr"`
	ClusterType      int      `json:"ClusterType"`
	QueryWord        string   `json:"QueryWord"`
	Image            Image    `json:"Image"`
	LabelDesc        string   `json:"LabelDesc,omitempty"`
	InterestCategory []string `json:"InterestCategory,omitempty"`
}
type FixedTopData struct {
	ID     int    `json:"Id"`
	Title  string `json:"Title"`
	URL    string `json:"Url"`
	Schema string `json:"Schema"`
}
